services:
    app:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        image: laravel-app
        container_name: thrive-cart-task
        volumes:
            - ../:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=thrive_cart_task
            - DB_USERNAME=root
            - DB_PASSWORD=root

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=thrive_cart_task
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
            interval: 10s
            retries: 5

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "9000:80"
        volumes:
            - ../:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    mysql-data:
